# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Enter a location category (e.g. Colleges, Parks, Mueseums etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Enter a city (e.g. Brisbane, Sydney, Perth etc.)', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Enter a country (e.g. Australia, New Zealand, China etc.)', max_length=255)),
                ('code', models.CharField(help_text=b'Enter a country code (e.g. AUS, NZ, CHN etc.)', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(help_text=b'Enter the street address (e.g. 123 Evergreen Tce)', max_length=255)),
                ('description', models.TextField(help_text=b'Enter a brief description of the location', max_length=1000)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFB299app.City')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFB299app.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Enter a region (region/province/state)', max_length=255)),
                ('code', models.CharField(help_text=b'Enter a region code (e.g. QLD, NSW, VIC etc.)', max_length=10)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFB299app.Country')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFB299app.Region'),
        ),
        migrations.AddField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFB299app.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFB299app.Region'),
        ),
    ]
