# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 04:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IFB299app', '0002_auto_20170922_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text=b'Enter a brief description of the event', max_length=1000)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFB299app.Location')),
            ],
        ),
    ]
